/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ConfirmedRouteImport } from './routes/confirmed'
import { Route as CourseRouteImport } from './routes/course'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RoomRouteImport } from './routes/room'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiGetWebinarMetricsRouteImport } from './routes/api/get-webinar-metrics'
import { Route as ApiGetWebinarTokenRouteImport } from './routes/api/get-webinar-token'
import { Route as ApiPublicEmailDispatchRouteImport } from './routes/api/public/email-dispatch'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'
import { Route as ApiPublicResendWebhookRouteImport } from './routes/api/public/resend-webhook'
import { Route as ApiPublicWebinarWebhookRouteImport } from './routes/api/public/webinar-webhook'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp-webhook'
import { Route as ApiPublicZeptomailWebhookRouteImport } from './routes/api/public/zeptomail-webhook'
import { Route as ApiRazorpayCreateOrderRouteImport } from './routes/api/razorpay/create-order'
import { Route as ApiRazorpayVerifyPaymentRouteImport } from './routes/api/razorpay/verify-payment'
import { Route as ApiWebhooksOppwebinarRouteImport } from './routes/api/webhooks/oppwebinar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmedRoute = ConfirmedRouteImport.update({
  id: '/confirmed',
  path: '/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseRoute = CourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoute = RoomRouteImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGetWebinarMetricsRoute = ApiGetWebinarMetricsRouteImport.update({
  id: '/api/get-webinar-metrics',
  path: '/api/get-webinar-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGetWebinarTokenRoute = ApiGetWebinarTokenRouteImport.update({
  id: '/api/get-webinar-token',
  path: '/api/get-webinar-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmailDispatchRoute = ApiPublicEmailDispatchRouteImport.update({
  id: '/api/public/email-dispatch',
  path: '/api/public/email-dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicResendWebhookRoute = ApiPublicResendWebhookRouteImport.update({
  id: '/api/public/resend-webhook',
  path: '/api/public/resend-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebinarWebhookRoute = ApiPublicWebinarWebhookRouteImport.update({
  id: '/api/public/webinar-webhook',
  path: '/api/public/webinar-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp-webhook',
    path: '/api/public/whatsapp-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicZeptomailWebhookRoute =
  ApiPublicZeptomailWebhookRouteImport.update({
    id: '/api/public/zeptomail-webhook',
    path: '/api/public/zeptomail-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRazorpayCreateOrderRoute = ApiRazorpayCreateOrderRouteImport.update({
  id: '/api/razorpay/create-order',
  path: '/api/razorpay/create-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRazorpayVerifyPaymentRoute =
  ApiRazorpayVerifyPaymentRouteImport.update({
    id: '/api/razorpay/verify-payment',
    path: '/api/razorpay/verify-payment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhooksOppwebinarRoute = ApiWebhooksOppwebinarRouteImport.update({
  id: '/api/webhooks/oppwebinar',
  path: '/api/webhooks/oppwebinar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/confirmed': typeof ConfirmedRoute
  '/course': typeof CourseRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/room': typeof RoomRoute
  '/terms': typeof TermsRoute
  '/api/get-webinar-metrics': typeof ApiGetWebinarMetricsRoute
  '/api/get-webinar-token': typeof ApiGetWebinarTokenRoute
  '/api/public/email-dispatch': typeof ApiPublicEmailDispatchRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/resend-webhook': typeof ApiPublicResendWebhookRoute
  '/api/public/webinar-webhook': typeof ApiPublicWebinarWebhookRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/public/zeptomail-webhook': typeof ApiPublicZeptomailWebhookRoute
  '/api/razorpay/create-order': typeof ApiRazorpayCreateOrderRoute
  '/api/razorpay/verify-payment': typeof ApiRazorpayVerifyPaymentRoute
  '/api/webhooks/oppwebinar': typeof ApiWebhooksOppwebinarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/confirmed': typeof ConfirmedRoute
  '/course': typeof CourseRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/room': typeof RoomRoute
  '/terms': typeof TermsRoute
  '/api/get-webinar-metrics': typeof ApiGetWebinarMetricsRoute
  '/api/get-webinar-token': typeof ApiGetWebinarTokenRoute
  '/api/public/email-dispatch': typeof ApiPublicEmailDispatchRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/resend-webhook': typeof ApiPublicResendWebhookRoute
  '/api/public/webinar-webhook': typeof ApiPublicWebinarWebhookRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/public/zeptomail-webhook': typeof ApiPublicZeptomailWebhookRoute
  '/api/razorpay/create-order': typeof ApiRazorpayCreateOrderRoute
  '/api/razorpay/verify-payment': typeof ApiRazorpayVerifyPaymentRoute
  '/api/webhooks/oppwebinar': typeof ApiWebhooksOppwebinarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/confirmed': typeof ConfirmedRoute
  '/course': typeof CourseRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/room': typeof RoomRoute
  '/terms': typeof TermsRoute
  '/api/get-webinar-metrics': typeof ApiGetWebinarMetricsRoute
  '/api/get-webinar-token': typeof ApiGetWebinarTokenRoute
  '/api/public/email-dispatch': typeof ApiPublicEmailDispatchRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/resend-webhook': typeof ApiPublicResendWebhookRoute
  '/api/public/webinar-webhook': typeof ApiPublicWebinarWebhookRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/public/zeptomail-webhook': typeof ApiPublicZeptomailWebhookRoute
  '/api/razorpay/create-order': typeof ApiRazorpayCreateOrderRoute
  '/api/razorpay/verify-payment': typeof ApiRazorpayVerifyPaymentRoute
  '/api/webhooks/oppwebinar': typeof ApiWebhooksOppwebinarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/confirmed'
    | '/course'
    | '/privacy'
    | '/resources'
    | '/room'
    | '/terms'
    | '/api/get-webinar-metrics'
    | '/api/get-webinar-token'
    | '/api/public/email-dispatch'
    | '/api/public/razorpay-webhook'
    | '/api/public/resend-webhook'
    | '/api/public/webinar-webhook'
    | '/api/public/whatsapp-webhook'
    | '/api/public/zeptomail-webhook'
    | '/api/razorpay/create-order'
    | '/api/razorpay/verify-payment'
    | '/api/webhooks/oppwebinar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/confirmed'
    | '/course'
    | '/privacy'
    | '/resources'
    | '/room'
    | '/terms'
    | '/api/get-webinar-metrics'
    | '/api/get-webinar-token'
    | '/api/public/email-dispatch'
    | '/api/public/razorpay-webhook'
    | '/api/public/resend-webhook'
    | '/api/public/webinar-webhook'
    | '/api/public/whatsapp-webhook'
    | '/api/public/zeptomail-webhook'
    | '/api/razorpay/create-order'
    | '/api/razorpay/verify-payment'
    | '/api/webhooks/oppwebinar'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/confirmed'
    | '/course'
    | '/privacy'
    | '/resources'
    | '/room'
    | '/terms'
    | '/api/get-webinar-metrics'
    | '/api/get-webinar-token'
    | '/api/public/email-dispatch'
    | '/api/public/razorpay-webhook'
    | '/api/public/resend-webhook'
    | '/api/public/webinar-webhook'
    | '/api/public/whatsapp-webhook'
    | '/api/public/zeptomail-webhook'
    | '/api/razorpay/create-order'
    | '/api/razorpay/verify-payment'
    | '/api/webhooks/oppwebinar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ConfirmedRoute: typeof ConfirmedRoute
  CourseRoute: typeof CourseRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRoute
  RoomRoute: typeof RoomRoute
  TermsRoute: typeof TermsRoute
  ApiGetWebinarMetricsRoute: typeof ApiGetWebinarMetricsRoute
  ApiGetWebinarTokenRoute: typeof ApiGetWebinarTokenRoute
  ApiPublicEmailDispatchRoute: typeof ApiPublicEmailDispatchRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
  ApiPublicResendWebhookRoute: typeof ApiPublicResendWebhookRoute
  ApiPublicWebinarWebhookRoute: typeof ApiPublicWebinarWebhookRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
  ApiPublicZeptomailWebhookRoute: typeof ApiPublicZeptomailWebhookRoute
  ApiRazorpayCreateOrderRoute: typeof ApiRazorpayCreateOrderRoute
  ApiRazorpayVerifyPaymentRoute: typeof ApiRazorpayVerifyPaymentRoute
  ApiWebhooksOppwebinarRoute: typeof ApiWebhooksOppwebinarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmed': {
      id: '/confirmed'
      path: '/confirmed'
      fullPath: '/confirmed'
      preLoaderRoute: typeof ConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course': {
      id: '/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof CourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room': {
      id: '/room'
      path: '/room'
      fullPath: '/room'
      preLoaderRoute: typeof RoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/get-webinar-metrics': {
      id: '/api/get-webinar-metrics'
      path: '/api/get-webinar-metrics'
      fullPath: '/api/get-webinar-metrics'
      preLoaderRoute: typeof ApiGetWebinarMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/get-webinar-token': {
      id: '/api/get-webinar-token'
      path: '/api/get-webinar-token'
      fullPath: '/api/get-webinar-token'
      preLoaderRoute: typeof ApiGetWebinarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email-dispatch': {
      id: '/api/public/email-dispatch'
      path: '/api/public/email-dispatch'
      fullPath: '/api/public/email-dispatch'
      preLoaderRoute: typeof ApiPublicEmailDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/resend-webhook': {
      id: '/api/public/resend-webhook'
      path: '/api/public/resend-webhook'
      fullPath: '/api/public/resend-webhook'
      preLoaderRoute: typeof ApiPublicResendWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webinar-webhook': {
      id: '/api/public/webinar-webhook'
      path: '/api/public/webinar-webhook'
      fullPath: '/api/public/webinar-webhook'
      preLoaderRoute: typeof ApiPublicWebinarWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp-webhook': {
      id: '/api/public/whatsapp-webhook'
      path: '/api/public/whatsapp-webhook'
      fullPath: '/api/public/whatsapp-webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/zeptomail-webhook': {
      id: '/api/public/zeptomail-webhook'
      path: '/api/public/zeptomail-webhook'
      fullPath: '/api/public/zeptomail-webhook'
      preLoaderRoute: typeof ApiPublicZeptomailWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/razorpay/create-order': {
      id: '/api/razorpay/create-order'
      path: '/api/razorpay/create-order'
      fullPath: '/api/razorpay/create-order'
      preLoaderRoute: typeof ApiRazorpayCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/razorpay/verify-payment': {
      id: '/api/razorpay/verify-payment'
      path: '/api/razorpay/verify-payment'
      fullPath: '/api/razorpay/verify-payment'
      preLoaderRoute: typeof ApiRazorpayVerifyPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/oppwebinar': {
      id: '/api/webhooks/oppwebinar'
      path: '/api/webhooks/oppwebinar'
      fullPath: '/api/webhooks/oppwebinar'
      preLoaderRoute: typeof ApiWebhooksOppwebinarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ConfirmedRoute: ConfirmedRoute,
  CourseRoute: CourseRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRoute,
  RoomRoute: RoomRoute,
  TermsRoute: TermsRoute,
  ApiGetWebinarMetricsRoute: ApiGetWebinarMetricsRoute,
  ApiGetWebinarTokenRoute: ApiGetWebinarTokenRoute,
  ApiPublicEmailDispatchRoute: ApiPublicEmailDispatchRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
  ApiPublicResendWebhookRoute: ApiPublicResendWebhookRoute,
  ApiPublicWebinarWebhookRoute: ApiPublicWebinarWebhookRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
  ApiPublicZeptomailWebhookRoute: ApiPublicZeptomailWebhookRoute,
  ApiRazorpayCreateOrderRoute: ApiRazorpayCreateOrderRoute,
  ApiRazorpayVerifyPaymentRoute: ApiRazorpayVerifyPaymentRoute,
  ApiWebhooksOppwebinarRoute: ApiWebhooksOppwebinarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
